server {
    listen 80;

    # Archivos estáticos de React
    location / {
        root /usr/share/nginx/html;
        index index.html;
        try_files $uri $uri/ /index.html;
    }

    # Redirigir llamadas API al backend Node.js
    location /api/ {
        proxy_pass http://backend-api:3001/api/;
        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection 'upgrade';
        proxy_set_header Host $host;
        proxy_cache_bypass $http_upgrade;
    }

    # Redirigir descargas de archivos/fotos al backend
    location /uploads/ {
        proxy_pass http://backend-api:3001/uploads/;
    }

    # Redirigir archivos públicos al backend
    location /public/ {
        proxy_pass http://backend-api:3001/public/;
    }
}
